[project]
name = "fft-viz"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nfdpy",
    "pyviewer",
    "research-utilities",
    "torchvision>=0.22.0",
]

[tool.uv.sources]
research-utilities = { git = "https://github.com/ShineiArakawa/research-utilities.git", rev = "v1.1.11" }
pyviewer = { git = "https://github.com/harskish/pyviewer.git" }
nfdpy = { git = "https://github.com/ShineiArakawa/nfdpy.git" }

[dependency-groups]
dev = ["scalene>=1.5.51"]
