[project]
name = "fft-viz"
version = "0.5.0"
description = "High-quality FFT visualization tool"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "nfdpy",
    "opencv-python>=4.11.0.86",
    "pyviewer-extended",
    "radpsd",
    "setuptools>=72.1.0",
    "torch>=2.7.1",
    "torchvision>=0.22.0",
]

[tool.uv.sources]
nfdpy = { git = "https://github.com/ShineiArakawa/nfdpy.git" }
pyviewer-extended = { git = "https://github.com/ShineiArakawa/pyviewer-extended.git", tag = "v0.3.0" }
radpsd = { git = "https://github.com/ShineiArakawa/radpsd.git" }
